r"""Held-out stability tests: the connection diagnostics tool (FR-005, FR-006).

Everything here goes over the real wire: a spawned ``python -m
katagiri.mcp_server`` in a sandbox, a real ``initialize`` handshake with a
declared client identity, and real ``tools/call`` frames. The contract under
test is contracts/connection_status.md.

BINDING: do not edit this file to make it pass. See MANIFEST.md.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    os.environ.get("KATAGIRI_HOLDOUT") != "1",
    reason="held-out 007 stability suite: run only at the gate with KATAGIRI_HOLDOUT=1",
)

TOOL = "connection_status"

#: contracts/connection_status.md, "Output (JSON object)".
CONTRACT_FIELDS: dict[str, type | tuple[type, ...]] = {
    "status": str,
    "katagiri_version": str,
    "python_version": str,
    "transport": str,
    "entry_point": str,
    "pid": int,
    "cwd": str,
    "config_path": str,
    "config_exists": bool,
    "db_path": str,
    "db_available": bool,
    "log_file_path": str,
    "client_info": dict,
    "secrets": dict,
    "changed_anything": bool,
}


# ---------------------------------------------------------------------------
# Registration + shape
# ---------------------------------------------------------------------------


def test_connection_status_is_listed_and_needs_no_arguments(sandbox, mcp_server):
    """FR-007: the tool is reachable through the normal registration seam."""
    client = mcp_server(sandbox)
    listed = client.call("tools/list")
    tools = {tool["name"]: tool for tool in listed["result"]["tools"]}
    assert TOOL in tools, f"{TOOL} is not in tools/list: {sorted(tools)}"
    schema = tools[TOOL].get("inputSchema") or {}
    assert not schema.get("required"), f"{TOOL} must take no arguments, got {schema.get('required')}"
    assert (tools[TOOL].get("description") or "").strip(), f"{TOOL} has no description"


def test_connection_status_returns_every_contract_field_with_the_right_type(
    holdout, sandbox, mcp_server
):
    """US2/1 + SC-002: one call, the whole runtime identity, in under five seconds."""
    client = mcp_server(sandbox)

    started = time.monotonic()
    payload = client.call_tool(TOOL)
    elapsed = time.monotonic() - started
    assert elapsed < holdout.DIAGNOSTIC_BUDGET_SECONDS, (
        f"{TOOL} took {elapsed:.2f}s; the contract budget is "
        f"{holdout.DIAGNOSTIC_BUDGET_SECONDS}s"
    )

    assert isinstance(payload, dict), payload
    missing = sorted(set(CONTRACT_FIELDS) - set(payload))
    assert not missing, f"{TOOL} omitted contract fields: {missing}"
    for field, expected in CONTRACT_FIELDS.items():
        value = payload[field]
        # bool is a subclass of int; the contract distinguishes them.
        if expected is int:
            assert isinstance(value, int) and not isinstance(value, bool), (
                f"{field} must be an integer, got {value!r}"
            )
        else:
            assert isinstance(value, expected), (
                f"{field} must be {expected}, got {type(value).__name__} ({value!r})"
            )

    assert payload["status"] == "ok", payload["status"]
    assert payload["transport"] == "stdio", payload["transport"]
    assert payload["changed_anything"] is False, "the diagnostic tool must be read-only"
    assert payload["pid"] > 0, payload["pid"]
    assert payload["pid"] == client.process.pid, (
        "the reported pid must be the answering process's own: "
        f"{payload['pid']} != {client.process.pid}"
    )
    for field in ("katagiri_version", "python_version", "entry_point", "cwd"):
        assert payload[field].strip(), f"{field} came back empty"
    assert "katagiri" in payload["entry_point"].casefold(), (
        "entry_point must say how this process was launched: " + payload["entry_point"]
    )


# ---------------------------------------------------------------------------
# US2/1 + guarantee 4 -- paths describe the answering process
# ---------------------------------------------------------------------------


def test_reported_paths_point_inside_the_launch_sandbox(sandbox, mcp_server):
    client = mcp_server(sandbox)
    payload = client.call_tool(TOOL)

    for field in ("config_path", "db_path", "log_file_path"):
        value = payload[field]
        assert value.strip(), f"{field} came back empty"
        assert sandbox.contains(value), (
            f"{field} points outside the sandbox this server was launched in: {value}"
        )
    assert Path(payload["config_path"]).name.endswith(".toml"), payload["config_path"]
    assert Path(payload["log_file_path"]).suffix == ".log", payload["log_file_path"]
    assert payload["config_exists"] is (Path(payload["config_path"]).exists()), (
        "config_exists disagrees with the path it reports"
    )


def test_client_identity_from_the_handshake_is_reported(holdout, sandbox, mcp_server):
    """US2/2: the server reports the client that introduced itself to it."""
    client = mcp_server(sandbox, client_name="kata-holdout-clientcheck", client_version="7.7.7")
    payload = client.call_tool(TOOL)

    info = payload["client_info"]
    assert set(info) >= {"name", "version"}, info
    assert info["name"] == "kata-holdout-clientcheck", info
    assert info["version"] == "7.7.7", info


def test_two_sandboxes_report_different_paths_and_pids(sandbox_factory, mcp_server):
    """US2/4: the endpoint distinguishes instances."""
    first = sandbox_factory()
    second = sandbox_factory()
    client_a = mcp_server(first)
    client_b = mcp_server(second)

    payload_a = client_a.call_tool(TOOL)
    payload_b = client_b.call_tool(TOOL)

    for field in ("config_path", "db_path", "log_file_path", "pid"):
        assert payload_a[field] != payload_b[field], (
            f"two instances launched from different sandboxes report the same {field}: "
            f"{payload_a[field]!r}"
        )
    assert first.contains(payload_a["config_path"]), payload_a["config_path"]
    assert second.contains(payload_b["config_path"]), payload_b["config_path"]
    assert not first.contains(payload_b["db_path"]), "instance B reports instance A's database"


# ---------------------------------------------------------------------------
# FR-006 -- degraded states are data, never exceptions
# ---------------------------------------------------------------------------


def test_db_available_is_true_when_the_sandbox_database_exists(sandbox, mcp_server):
    assert sandbox.db_path.is_file(), "this sandbox is supposed to carry a seeded database"
    payload = mcp_server(sandbox).call_tool(TOOL)
    assert payload["db_available"] is True, payload
    assert Path(payload["db_path"]) == sandbox.db_path, payload["db_path"]


def test_db_available_is_false_when_the_sandbox_has_no_database(sandbox_factory, mcp_server):
    """Edge case: unreachable database -> a flag, not a crash, and no repair."""
    box = sandbox_factory(seed=False)
    assert not box.db_path.exists()

    payload = mcp_server(box).call_tool(TOOL)

    assert payload["status"] == "ok", payload
    assert payload["db_available"] is False, payload
    assert box.contains(payload["db_path"]), payload["db_path"]
    assert payload["changed_anything"] is False, payload
    assert not Path(payload["db_path"]).exists(), (
        "a read-only diagnostic must not create the database it reports on"
    )


def test_a_missing_config_file_is_reported_as_data_not_an_error(sandbox, mcp_server):
    """Edge case: config absent at call time -> answered, with config_exists false.

    The file is removed after the handshake, which is the honest way to reach
    this state over the wire: the reported flag must come from resolving the
    path when asked, not from something cached at start-up.
    """
    client = mcp_server(sandbox)
    sandbox.config_path.unlink()
    assert not sandbox.config_path.exists()

    payload = client.call_tool(TOOL)

    assert payload["status"] == "ok", payload
    assert payload["config_exists"] is False, payload
    assert sandbox.contains(payload["config_path"]), payload["config_path"]
    assert payload["changed_anything"] is False, payload


def test_a_client_that_sends_no_identity_is_reported_as_unknown(sandbox, mcp_server):
    """Edge case: "Client that sends no identity -> 'unknown client', not omitted"."""
    client = mcp_server(sandbox, handshake=False)
    response = client.call(
        "initialize", {"protocolVersion": "2024-11-05", "capabilities": {}}
    )
    if "error" in response:
        pytest.skip("this MCP SDK rejects an initialize without clientInfo; nothing to diagnose")
    client.notify("notifications/initialized")

    payload = client.call_tool(TOOL)

    info = payload["client_info"]
    assert set(info) >= {"name", "version"}, f"client_info must keep its shape: {info}"
    assert info["name"], "an unidentified client must be named 'unknown', not left blank"
    assert info["name"].casefold() == "unknown", info


# ---------------------------------------------------------------------------
# FR-011 -- presence flags only, no secret values anywhere
# ---------------------------------------------------------------------------


def test_secrets_are_reported_as_presence_flags_only(holdout, sandbox, mcp_server):
    """US2/3 + data-model: a set/unset map covering the credential-bearing keys."""
    payload = mcp_server(sandbox).call_tool(TOOL)

    secrets = payload["secrets"]
    assert secrets, "the secrets presence map is empty"
    for field, value in secrets.items():
        assert value in ("set", "unset"), (
            f"secrets[{field!r}] must be 'set' or 'unset', got {value!r}"
        )
    assert set(secrets) >= {"obsidian_api_token", "mokuro_shared_secret"}, (
        f"the presence map must cover both credential fields: {sorted(secrets)}"
    )
    # The sandbox config sets exactly one of the two.
    assert secrets["obsidian_api_token"] == "set", secrets
    assert secrets["mokuro_shared_secret"] == "unset", secrets


def test_the_canary_secret_never_appears_in_the_response_or_on_stderr(
    holdout, sandbox, mcp_server
):
    """SC-004: enforced by a leak check, not by review."""
    assert holdout.CANARY_TOKEN in sandbox.config_path.read_text(encoding="utf-8"), (
        "the canary was not planted in the sandbox config"
    )
    client = mcp_server(sandbox)

    payload = client.call_tool(TOOL)
    raw_frame = client.last_raw
    blob = json.dumps(payload, ensure_ascii=False)

    holdout.assert_no_canary(blob, where=f"the {TOOL} payload")
    holdout.assert_no_canary(raw_frame, where=f"the raw {TOOL} frame")
    holdout.assert_no_traceback(blob, where=f"the {TOOL} payload")

    stderr = client.close()
    holdout.assert_no_canary(stderr, where="the server's stderr")
    holdout.assert_no_traceback(stderr, where="the server's stderr")
