r"""Held-out stability tests: the install chain (FR-001, FR-002, FR-003).

Every test drives the real installer as a subprocess, in a throwaway sandbox,
with ``LOCALAPPDATA`` and ``KATAGIRI_CONFIG`` redirected. Nothing here reads or
writes the developer's real ``%LOCALAPPDATA%\Katagiri``, and nothing here
registers a Windows scheduled task.

BINDING: do not edit this file to make it pass. See MANIFEST.md.
"""

from __future__ import annotations

import os
import re
import tomllib

import pytest

pytestmark = pytest.mark.skipif(
    os.environ.get("KATAGIRI_HOLDOUT") != "1",
    reason="held-out 007 stability suite: run only at the gate with KATAGIRI_HOLDOUT=1",
)


# ---------------------------------------------------------------------------
# FR-001 -- non-interactive mode, end to end
# ---------------------------------------------------------------------------


def test_yes_mode_completes_in_an_empty_sandbox_and_writes_a_config(
    holdout, sandbox_factory, run_installer
):
    """US1/1: no config file in, config file out, no prompt anyone must answer.

    stdin is closed, so a wizard that still *needs* an answer would either
    crash or hang; completing means the non-interactive path is real.
    """
    box = sandbox_factory(config=False)
    assert not box.config_path.exists(), "the sandbox must start without a config file"

    proc = run_installer(box, "--yes")

    assert proc.returncode == 0, proc.stdout[-4000:] + proc.stderr[-4000:]
    assert box.config_path.is_file(), "--yes must write a config file into the sandbox"
    parsed = tomllib.loads(box.config_path.read_text(encoding="utf-8"))
    assert parsed, "the written config must carry at least one resolved setting"
    assert box.contains(parsed["db_path"]), (
        "the config the installer wrote points its database outside the sandbox: "
        f"{parsed['db_path']}"
    )


def test_yes_mode_reports_a_per_step_status_summary(holdout, sandbox_factory, run_installer):
    """US1/1: every step announces itself, and the doctor table closes the run."""
    total = holdout.TOTAL_INSTALLER_STEPS
    box = sandbox_factory(config=False)

    proc = run_installer(box, "--yes")
    assert proc.returncode == 0, proc.stdout[-4000:]

    for step in range(1, total + 1):
        assert f"[{step}/{total}]" in proc.stdout, (
            f"step {step} of {total} is missing from the run summary:\n" + proc.stdout[-4000:]
        )

    rows = holdout.doctor_rows(proc.stdout)
    assert len(rows) >= 8, f"the closing doctor table looks truncated: {rows}"
    assert any(status == "READY" for _, status, _ in rows), rows

    # FR-010: the same story must be readable from the log file afterwards.
    log = box.log_text()
    assert log, "the installer wrote no log file into the sandbox"
    logged_steps = set(re.findall(rf"step (\d+)/{total}", log))
    assert len(logged_steps) >= total - 1, (
        "the log file does not record the wizard's steps: " + log[-3000:]
    )


# ---------------------------------------------------------------------------
# FR-002 -- doctor-only mode
# ---------------------------------------------------------------------------


def test_check_mode_on_a_broken_sandbox_exits_nonzero_and_names_the_failing_step(
    holdout, sandbox_factory, run_installer
):
    """US1/2: nothing installed -> non-zero exit and the failing rows named."""
    box = sandbox_factory(config=False, seed=False)

    proc = run_installer(box, "--check", timeout=60.0)

    assert proc.returncode != 0, (
        "doctor mode must report an unready machine through its exit code:\n" + proc.stdout[-3000:]
    )
    rows = holdout.doctor_rows(proc.stdout)
    assert rows, "doctor mode printed no readable status table:\n" + proc.stdout[-3000:]
    missing = [(component, detail) for component, status, detail in rows if status == "MISSING"]
    assert missing, f"nothing was reported MISSING in an empty sandbox: {rows}"
    for component, detail in missing:
        assert component.strip(), f"a MISSING row has no component name: {rows}"
        assert detail.strip(), f"the MISSING row for {component!r} explains nothing"
    names = " ".join(component.casefold() for component, _ in missing)
    assert "config" in names, (
        "a sandbox with no config.toml must name the config step as missing: " + str(missing)
    )


def test_check_mode_changes_nothing_except_its_own_log(holdout, sandbox_factory, run_installer):
    """US1/2: doctor mode is read-only.

    Interpretation (recorded in MANIFEST.md): the doctor's own log file is
    excluded from the "changes nothing" claim, because FR-010 requires the run
    to be reconstructible from the log afterwards. Everything else in the
    sandbox -- config, database, scratch, snapshots -- must be byte-identical.
    """
    box = sandbox_factory()
    # A complete config first: --check on a partial file may legitimately
    # append commented templates for keys it has never seen.
    first = run_installer(box, "--yes")
    assert first.returncode == 0, first.stdout[-3000:]

    before = box.snapshot()
    config_before = box.config_path.read_bytes()
    db_key = box.db_path.relative_to(box.root).as_posix()
    assert db_key in before, f"the database must be part of the compared snapshot: {db_key}"

    proc = run_installer(box, "--check", timeout=60.0)
    after = box.snapshot()

    assert proc.stdout, "doctor mode printed nothing"
    added = sorted(set(after) - set(before))
    removed = sorted(set(before) - set(after))
    changed = sorted(key for key in set(before) & set(after) if before[key] != after[key])
    assert not added, f"--check created {added}"
    assert not removed, f"--check deleted {removed}"
    assert not changed, f"--check modified {changed}"
    assert box.config_path.read_bytes() == config_before, "--check rewrote config.toml"


# ---------------------------------------------------------------------------
# Idempotence (installer contract: "every step is idempotent and safe to re-run")
# ---------------------------------------------------------------------------


def test_running_yes_mode_twice_still_succeeds_and_keeps_the_same_config(
    holdout, sandbox_factory, run_installer
):
    total = holdout.TOTAL_INSTALLER_STEPS
    box = sandbox_factory(config=False)

    first = run_installer(box, "--yes")
    assert first.returncode == 0, first.stdout[-3000:]
    db_after_first = tomllib.loads(box.config_path.read_text(encoding="utf-8"))["db_path"]

    second = run_installer(box, "--yes")
    assert second.returncode == 0, second.stdout[-3000:]

    parsed = tomllib.loads(box.config_path.read_text(encoding="utf-8"))
    assert parsed["db_path"] == db_after_first, "a re-run relocated the database"
    for step in range(1, total + 1):
        assert f"[{step}/{total}]" in second.stdout, (
            f"the second run skipped step {step}:\n" + second.stdout[-3000:]
        )
    rows = holdout.doctor_rows(second.stdout)
    assert any(status == "READY" for _, status, _ in rows), rows


# ---------------------------------------------------------------------------
# FR-003 -- interactive retry / skip / abort
# ---------------------------------------------------------------------------


def _sandbox_with_one_broken_step(sandbox_factory):
    """A sandbox whose Anki step cannot succeed: its profile dir is absent."""
    box = sandbox_factory()
    box.write_config(anki_data_dir=box.root / "absent-anki-profile")
    return box


def test_aborting_the_wizard_records_the_step_it_died_on_in_the_log_file(
    holdout, sandbox_factory, run_installer
):
    """Edge case: "Wizard aborted mid-run -> abort is logged with the step number".

    The scripted stdin answers the config step's prompts with "keep", then
    answers every failure prompt with Abort.
    """
    total = holdout.TOTAL_INSTALLER_STEPS
    box = _sandbox_with_one_broken_step(sandbox_factory)

    proc = run_installer(box, stdin_text="\n\n\n" + "a\n" * 8)

    match = re.search(r"aborted at step (\d+) \(([^)]+)\)", proc.stdout)
    assert match, (
        "choosing Abort at a failed step must say so on the console:\n" + proc.stdout[-4000:]
    )
    step_number, step_label = match.group(1), match.group(2)

    log = box.log_text()
    assert log, "the aborted wizard wrote no log file"
    abort_lines = [line for line in log.splitlines() if "abort" in line.casefold()]
    assert abort_lines, "the abort is not recorded in the log file:\n" + log[-3000:]
    assert any(step_number in line and step_label in line for line in abort_lines), (
        f"no log record names the aborted step ({step_number} {step_label!r}):\n"
        + "\n".join(abort_lines)
    )
    # FR-010: the failure that triggered the abort must be reconstructible too.
    assert f"step {step_number}/{total}" in log, log[-3000:]
    assert "ACTION NEEDED" in log, "the failing step's outcome is not in the log:\n" + log[-3000:]


def test_a_skipped_step_lets_the_wizard_finish_and_shows_up_in_the_summary(
    holdout, sandbox_factory, run_installer
):
    """US1/3: Skip (the default, and what EOF means) continues the wizard.

    stdin is closed, so every failure prompt takes its default -- Skip -- and
    the run must still reach the closing doctor summary and exit 0.
    """
    total = holdout.TOTAL_INSTALLER_STEPS
    box = _sandbox_with_one_broken_step(sandbox_factory)

    proc = run_installer(box)

    assert proc.returncode == 0, (
        "the wizard always exits 0; --check is the mode with a status exit code:\n"
        + proc.stdout[-4000:]
    )
    assert "[R]etry / [S]kip / [A]bort" in proc.stdout, (
        "a failed step must offer Retry/Skip/Abort:\n" + proc.stdout[-4000:]
    )
    assert f"[{total}/{total}]" in proc.stdout, (
        "the wizard did not reach its closing summary after a skip:\n" + proc.stdout[-4000:]
    )
    rows = holdout.doctor_rows(proc.stdout)
    assert rows, "no doctor summary after a skipped step:\n" + proc.stdout[-4000:]
    not_ready = [component for component, status, _ in rows if status != "READY"]
    assert not_ready, "a skipped step must leave something short of READY in the summary"

    log = box.log_text()
    assert "ACTION NEEDED" in log, (
        "the skipped step's failing outcome is not in the log file:\n" + log[-3000:]
    )


# ---------------------------------------------------------------------------
# Isolation (FR-001: "mutates nothing outside the sandbox")
# ---------------------------------------------------------------------------


def test_a_sandboxed_install_creates_nothing_in_the_real_app_data(
    holdout, sandbox_factory, run_installer
):
    """The whole install chain must stay inside the redirected sandbox.

    Two claims, both safe on a machine that already has a real install: no new
    entry appears under the real ``%LOCALAPPDATA%\\Katagiri``, and the real
    config file is untouched. (Its log file is deliberately not inspected: an
    unrelated Katagiri process may be appending to it while this test runs.)
    """
    names_before = holdout.real_app_data_names()
    config_before = holdout.real_config_fingerprint()

    box = sandbox_factory(config=False)
    proc = run_installer(box, "--yes")
    assert proc.returncode == 0, proc.stdout[-3000:]

    names_after = holdout.real_app_data_names()
    if names_before is None:
        assert names_after is None, (
            "a sandboxed install created the real %LOCALAPPDATA%\\Katagiri directory"
        )
    else:
        assert names_after is not None, "the real app-data directory disappeared"
        new_names = names_after - names_before
        assert not new_names, f"a sandboxed install added {sorted(new_names)} to the real app data"

    assert holdout.real_config_fingerprint() == config_before, (
        "a sandboxed install rewrote the real config.toml"
    )
    # And the sandbox really was where the work happened.
    assert box.config_path.is_file()
    assert box.log_files(), "the sandboxed run left no log file in the sandbox"
