r"""Held-out stability tests: after-the-fact traceability (FR-008..FR-011).

The question these tests ask is US3's: "the console is long closed -- can the
operator still reconstruct what happened from the log location alone?" So every
assertion here reads files under the sandbox, never the captured console output,
except where the claim is explicitly about a stream (stdout must stay
protocol-clean).

BINDING: do not edit this file to make it pass. See MANIFEST.md.
"""

from __future__ import annotations

import json
import os
import re

import pytest

pytestmark = pytest.mark.skipif(
    os.environ.get("KATAGIRI_HOLDOUT") != "1",
    reason="held-out 007 stability suite: run only at the gate with KATAGIRI_HOLDOUT=1",
)


def _sandbox_log_files(box):
    """Log files in the documented log home: ``<sandbox>\\Katagiri\\logs``."""
    if not box.logs_dir.is_dir():
        return []
    return sorted(path for path in box.logs_dir.iterdir() if path.is_file())


def _text_of(paths) -> str:
    return "\n".join(path.read_text(encoding="utf-8", errors="replace") for path in paths)


# ---------------------------------------------------------------------------
# FR-008 -- the bootstrap launcher leaves a file behind
# ---------------------------------------------------------------------------


def test_a_bootstrap_launch_failure_is_recorded_in_a_log_file(
    sandbox, bootstrap_repo, run_bootstrap
):
    """US3/1: a launch that dies before the server starts must not die silently.

    The launcher is aimed at an interpreter and a server module that do not
    exist, which is the realistic pre-exec failure (a checkout with no venv).
    The console this runs on is exactly the one a real MCP client throws away.
    """
    repo = bootstrap_repo(sandbox)

    proc = run_bootstrap(sandbox, repo, "--stdio-bootstrap")

    assert proc.returncode != 0, (
        "a bootstrap that cannot launch the server must fail loudly:\n" + proc.stderr[-3000:]
    )

    logs = _sandbox_log_files(sandbox)
    assert logs, (
        "nothing was written to the log home "
        f"({sandbox.logs_dir}); a failed launch left only the dead console.\n"
        "--- the console it left ---\n" + proc.stderr[-3000:]
    )
    text = _text_of(logs)
    assert any(
        word in text.casefold() for word in ("bootstrap", "launch")
    ), f"no log record names the phase that failed:\n{text[-3000:]}"
    reason_tokens = (repo.bogus_python.name, repo.bogus_module, "KATAGIRI_PYTHON")
    assert any(token in text for token in reason_tokens), (
        "the failure reason is not reconstructible from the log file alone "
        f"(looked for any of {reason_tokens}):\n{text[-3000:]}"
    )


def test_a_bootstrap_launch_keeps_stdout_protocol_clean(sandbox, bootstrap_repo, run_bootstrap):
    """FR-008: diagnostics go to stderr/file; stdout belongs to JSON-RPC."""
    repo = bootstrap_repo(sandbox)

    proc = run_bootstrap(sandbox, repo, "--stdio-bootstrap")

    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        try:
            json.loads(line)
        except json.JSONDecodeError:
            pytest.fail(
                "the bootstrap wrote non-protocol text to stdout during a "
                f"client-driven launch: {line!r}"
            )
    assert proc.stderr.strip(), "the bootstrap reported nothing at all on stderr"


# ---------------------------------------------------------------------------
# FR-009 -- connection lifecycle in the server log
# ---------------------------------------------------------------------------


def test_the_server_log_records_the_client_identity_from_the_handshake(
    holdout, sandbox, mcp_server
):
    """US3/2: which client connected must be readable afterwards."""
    client = mcp_server(sandbox, client_name="kata-holdout-logcheck", client_version="3.1.4")
    client.call_tool("ping")
    client.close()

    text = _text_of(_sandbox_log_files(sandbox))
    assert text, "the server wrote no log file into the sandbox"
    identity_lines = [line for line in text.splitlines() if "kata-holdout-logcheck" in line]
    assert identity_lines, (
        "no log record names the client that identified itself at the handshake:\n"
        + text[-3000:]
    )
    assert any("3.1.4" in line for line in identity_lines), (
        "the client's version is not recorded:\n" + "\n".join(identity_lines)
    )


def test_the_server_log_carries_enough_instance_identity_to_tell_instances_apart(
    holdout, sandbox, mcp_server
):
    """Edge case: two instances sharing one log file must be distinguishable."""
    client = mcp_server(sandbox)
    client.call_tool("ping")
    pid = client.process.pid
    accepted = {pid} | holdout.direct_child_pids(pid)
    client.close()

    text = _text_of(_sandbox_log_files(sandbox))
    # amended per user decision 2026-08-24 (tasks.md T021): venv launcher shim makes Popen.pid the shim, interpreter is its direct child
    assert any(str(p) in text for p in accepted), (
        f"the log does not carry the answering instance's pid ({pid}); concurrent "
        "instances sharing a log file cannot be told apart:\n" + text[-3000:]
    )


def test_the_server_log_records_one_line_per_tool_call(sandbox, mcp_server):
    """US3/2: name, outcome and duration for every call."""
    client = mcp_server(sandbox)
    client.call_tool("ping")
    client.call_tool("security_status")
    client.close()

    text = _text_of(_sandbox_log_files(sandbox))
    for tool in ("ping", "security_status"):
        lines = [line for line in text.splitlines() if f"tool {tool}" in line]
        assert lines, f"no per-call record for {tool}:\n{text[-3000:]}"
        assert any("ok" in line for line in lines), f"{tool}'s outcome is not recorded: {lines}"
        assert any(re.search(r"\d+(\.\d+)?\s*ms", line) for line in lines), (
            f"{tool}'s duration is not recorded: {lines}"
        )


def test_the_server_stdout_carries_only_json_rpc_frames(sandbox, mcp_server):
    """US1/4: protocol-clean stdout, diagnostics on stderr."""
    client = mcp_server(sandbox)
    client.call_tool("ping")
    stderr = client.close()

    lines = [line.decode("utf-8", "replace") for line in client.stdout_lines]
    assert lines, "the server said nothing on stdout at all"
    for line in lines:
        if not line.strip():
            continue
        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            pytest.fail(f"non-protocol text on the server's stdout: {line!r}")
        assert message.get("jsonrpc") == "2.0", f"not a JSON-RPC frame: {line!r}"
    assert "starting katagiri" in stderr, (
        "the start-up line belongs on stderr, where clients look for it:\n" + stderr[-2000:]
    )


# ---------------------------------------------------------------------------
# FR-010 -- an installer failure is reconstructible from the log alone
# ---------------------------------------------------------------------------


def test_an_installer_failure_is_reconstructible_from_the_log_file_alone(
    holdout, sandbox, run_installer
):
    """US3 independent test: step label, outcome, and error text, in the file."""
    total = holdout.TOTAL_INSTALLER_STEPS
    sandbox.write_config(anki_data_dir=sandbox.root / "absent-anki-profile")

    proc = run_installer(sandbox, "--yes")
    assert proc.returncode == 0, proc.stdout[-3000:]

    text = _text_of(_sandbox_log_files(sandbox))
    assert text, "the installer wrote no log file into the sandbox"
    failures = [
        line
        for line in text.splitlines()
        if "ACTION NEEDED" in line and re.search(rf"step \d+/{total}", line)
    ]
    assert failures, (
        "a broken step's failure is not reconstructible from the log file:\n" + text[-4000:]
    )
    for line in failures:
        match = re.search(rf"step (\d+)/{total} ([^:]+): ACTION NEEDED(.*)", line)
        assert match, f"a failure record is not parseable: {line!r}"
        assert match.group(2).strip(), f"the failing step has no label: {line!r}"
        assert match.group(3).strip(" ()"), f"the failure carries no error text: {line!r}"


# ---------------------------------------------------------------------------
# FR-011 -- no secret value in any log record
# ---------------------------------------------------------------------------


def test_no_log_file_under_the_sandbox_contains_the_canary_secret(
    holdout, sandbox, run_installer, mcp_server
):
    """SC-004 across every writer this feature touches: installer and server."""
    assert holdout.CANARY_TOKEN in sandbox.config_path.read_text(encoding="utf-8")

    installed = run_installer(sandbox, "--yes")
    assert installed.returncode == 0, installed.stdout[-3000:]

    client = mcp_server(sandbox)
    client.call_tool("ping")
    client.call_tool("security_status")
    stderr = client.close()

    files = sandbox.log_files()
    assert files, "no log files to check -- the leak check would be vacuous"
    for path in files:
        holdout.assert_no_canary(
            path.read_text(encoding="utf-8", errors="replace"),
            where=f"the log file {path.name}",
        )
    holdout.assert_no_canary(installed.stdout, where="the installer's stdout")
    holdout.assert_no_canary(installed.stderr, where="the installer's stderr")
    holdout.assert_no_canary(stderr, where="the server's stderr")
    holdout.assert_no_canary(client.raw_stdout, where="the server's stdout frames")
