r"""Held-out stability tests: side-by-side instances (US5, FR-014..FR-017).

The design under test is research.md D9: one override, ``KATAGIRI_DATA_HOME``,
honored where the instance root is resolved, with ``config.toml``, the database
and ``logs/`` moving as one unit; ``KATAGIRI_CONFIG`` > ``KATAGIRI_DATA_HOME`` >
default precedence; an invalid override rejected loudly rather than falling back
to the default home; the installer's ``--data-home PATH`` flag persisting the
wiring in the checkout it ran from; and ``connection_status`` reporting
``data_home`` + ``data_home_source`` so two instances are told apart in one call.

Isolation, on top of the suite-wide contract in conftest.py:

* "the default home" always means ``<sandbox>/appdata/Katagiri``, because
  ``LOCALAPPDATA`` is redirected -- the real ``%LOCALAPPDATA%\Katagiri`` is
  never a candidate for anything asserted here;
* every child gets ``KATAGIRI_DATA_HOME`` deleted unless the test sets it, so a
  value in the gate operator's shell cannot make a test pass or fail;
* the ``--data-home`` tests run the installer inside a **mirrored checkout**
  (a copy of ``src/katagiri`` plus an ``agent/`` skeleton, on ``PYTHONPATH``)
  so a checkout-relative writer lands in the mirror; the real ``agent/.env`` is
  additionally snapshotted and byte-restored by a guard fixture, so even an
  implementation that resolves the checkout from the installed package cannot
  leave the developer's file modified.

BINDING: do not edit this file to make it pass. See MANIFEST.md.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    os.environ.get("KATAGIRI_HOLDOUT") != "1",
    reason="held-out 007 stability suite: run only at the gate with KATAGIRI_HOLDOUT=1",
)

TOOL = "connection_status"

#: An install into a pre-seeded data home is a seconds-long run; the cold budget
#: covers a home whose database name the implementation resolves elsewhere, so a
#: real dictionary import happens instead.
INSTALL_BUDGET = 120.0
INSTALL_COLD_BUDGET = 300.0

#: An override that must be rejected, not resolved.
RELATIVE_HOME_NAME = "kata-holdout-relative-home"


# ---------------------------------------------------------------------------
# Helpers (module-local on purpose: this file adds nothing to the shared
# fixtures beyond the additive Sandbox.env_unset / use_data_home seam)
# ---------------------------------------------------------------------------


def same_path(left: str | Path, right: str | Path) -> bool:
    """Windows-honest path equality (case-folded, resolved)."""
    return str(Path(left).resolve()).casefold() == str(Path(right).resolve()).casefold()


def inside(root: str | Path, candidate: str | Path) -> bool:
    root_text = str(Path(root).resolve()).casefold()
    return str(Path(candidate).resolve()).casefold().startswith(root_text)


def tree_fingerprint(root: Path) -> dict[str, tuple[int, int] | str]:
    """Relative name -> fingerprint for everything under ``root``."""
    out: dict[str, tuple[int, int] | str] = {}
    if not root.exists():
        return out
    for path in sorted(root.rglob("*")):
        rel = path.relative_to(root).as_posix()
        if path.is_dir():
            out[rel] = "DIR"
        else:
            stat = path.stat()
            out[rel] = (stat.st_size, stat.st_mtime_ns)
    return out


def files_under(root: Path) -> list[Path]:
    return sorted(path for path in root.rglob("*") if path.is_file()) if root.exists() else []


def log_files_under(root: Path) -> list[Path]:
    """Log files anywhere under ``root`` (rotated ``.log.1`` siblings included)."""
    return [path for path in files_under(root) if ".log" in path.name]


def config_db_path(config_file: Path) -> str:
    """The ``db_path`` the installer chose, read from the config it wrote."""
    parsed = tomllib.loads(config_file.read_text(encoding="utf-8"))
    assert "db_path" in parsed, f"the written config names no database: {sorted(parsed)}"
    return parsed["db_path"]


def make_home(tmp_path: Path, holdout, name: str, *, create: bool = True, seed: bool = True):
    """A fresh instance data home. Returns ``(path, seeded)``.

    Seeding drops the cached JMdict database at ``<home>/katagiri.db`` so a full
    install finishes in seconds. It deliberately does not make any assertion
    true: what the tests check is where the *installer* points the config it
    writes, and that the default home stays empty.
    """
    home = tmp_path / f"{holdout.SANDBOX_MARKER}-home-{name}"
    seeded = False
    if create:
        home.mkdir(parents=True, exist_ok=True)
        if seed:
            template = holdout.jmdict_template()
            if template is not None:
                shutil.copy2(template, home / "katagiri.db")
                seeded = True
    return home, seeded


def budget(seeded: bool) -> float:
    return INSTALL_BUDGET if seeded else INSTALL_COLD_BUDGET


def report(proc: subprocess.CompletedProcess[str], label: str) -> str:
    return (
        f"{label} exited {proc.returncode}\n--- stdout ---\n{(proc.stdout or '')[-4000:]}\n"
        f"--- stderr ---\n{(proc.stderr or '')[-4000:]}"
    )


# ---------------------------------------------------------------------------
# Mirrored checkout (for the --data-home flag, which persists per-checkout state)
# ---------------------------------------------------------------------------


@dataclass
class Mirror:
    """A throwaway checkout the real installer can run *as*."""

    root: Path
    src: Path
    agent_dir: Path
    env_file: Path


@pytest.fixture
def mirror_checkout(tmp_path) -> Mirror:
    """A copy of the package plus an ``agent/`` skeleton, importable and cwd-able.

    ``PYTHONPATH`` points at the copy, so ``python -m katagiri.installer``
    imports the mirrored files and any checkout resolution derived from the
    module's own location, or from the working directory, lands inside the
    mirror instead of the developer's repository. ``vendor/`` is not copied
    (1.3 GB): the steps that need it report themselves as not ready, which the
    wizard is required to survive anyway.

    Deliberately per-test, not shared: ``--data-home`` *persists* state in the
    checkout it ran in, and a mirror reused across tests would let one test's
    wiring line be read as another's.
    """
    repo_root = Path(__file__).resolve().parents[3]
    root = tmp_path / "kata-holdout-mirror"
    root.mkdir()
    src = root / "src"
    src.mkdir()
    shutil.copytree(
        repo_root / "src" / "katagiri",
        src / "katagiri",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    for name in ("pyproject.toml", "README.md"):
        source = repo_root / name
        if source.is_file():
            shutil.copy2(source, root / name)
    agent_dir = root / "agent"
    (agent_dir / "scripts").mkdir(parents=True)
    bootstrap = repo_root / "agent" / "scripts" / "setup.py"
    if bootstrap.is_file():
        shutil.copy2(bootstrap, agent_dir / "scripts" / "setup.py")
    env_file = agent_dir / ".env"
    env_file.write_text("PYTHONUTF8=1\n", encoding="utf-8")
    return Mirror(root=root, src=src, agent_dir=agent_dir, env_file=env_file)


@pytest.fixture
def run_installer_in_mirror(mirror_checkout: Mirror):
    """Run the real installer with the mirrored checkout as both cwd and import root."""

    def run(box, *args: str, timeout: float = INSTALL_BUDGET, **extra_env: str):
        env = box.env(PYTHONPATH=str(mirror_checkout.src), **extra_env)
        try:
            return subprocess.run(
                [sys.executable, "-m", "katagiri.installer", *args],
                cwd=str(mirror_checkout.root),
                env=env,
                stdin=subprocess.DEVNULL,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout,
            )
        except subprocess.TimeoutExpired as exc:  # pragma: no cover - a wedged installer
            stdout = exc.stdout if isinstance(exc.stdout, str) else ""
            stderr = exc.stderr if isinstance(exc.stderr, str) else ""
            pytest.fail(
                f"installer {args} in the mirrored checkout did not finish within "
                f"{timeout}s\n--- stdout ---\n{stdout[-3000:]}\n--- stderr ---\n{stderr[-3000:]}"
            )

    return run


@dataclass
class CheckoutEnvGuard:
    """Byte-restores the real checkout's ``agent/.env``, whatever a run did to it."""

    path: Path
    existed: bool
    #: Lines the file already had before the run. A developer's real checkout
    #: may legitimately already be wired to an instance; only lines this run
    #: added count as evidence about this run.
    baseline_lines: tuple[str, ...] = ()

    def text_now(self) -> str:
        if not self.path.is_file():
            return ""
        return self.path.read_text(encoding="utf-8", errors="replace")

    def added_text(self) -> str:
        """Only the lines that were not in the file before the run."""
        baseline = set(self.baseline_lines)
        return "\n".join(
            line for line in self.text_now().splitlines() if line not in baseline
        )


@pytest.fixture
def real_env_file_guard(holdout):
    """Snapshot + restore ``<repo>/agent/.env`` around a ``--data-home`` run.

    The flag is specified to persist instance wiring in "the checkout", and an
    implementation may resolve that from the installed package's own location --
    which, in this repository, is the developer's real checkout. The mirrored
    checkout is the primary defence; this is the backstop that makes the
    developer's file untouchable in fact, not just by intent.
    """
    path = holdout.REPO_ROOT / "agent" / ".env"
    existed = path.is_file()
    original = path.read_bytes() if existed else None
    baseline = tuple(
        path.read_text(encoding="utf-8", errors="replace").splitlines() if existed else ()
    )
    try:
        yield CheckoutEnvGuard(path=path, existed=existed, baseline_lines=baseline)
    finally:
        if original is None:
            if path.is_file():  # pragma: no cover - only if the run created it
                path.unlink()
        elif path.read_bytes() != original:  # pragma: no cover - only if the run wrote it
            path.write_bytes(original)


# ---------------------------------------------------------------------------
# FR-014 -- one override moves config + database + logs as a unit
# ---------------------------------------------------------------------------


def test_a_data_home_override_puts_config_database_and_logs_under_it(
    holdout, tmp_path, sandbox_factory, run_installer
):
    """US5/2 + FR-014: the whole instance lives inside the override, and only there."""
    box = sandbox_factory(config=False, seed=False)
    home, seeded = make_home(tmp_path, holdout, "solo")
    box.use_data_home(home)

    proc = run_installer(box, "--yes", timeout=budget(seeded))
    assert proc.returncode == 0, report(proc, "the installer under a data home")

    config_file = home / "config.toml"
    assert config_file.is_file(), (
        f"no config.toml under the data home {home}; the installer wrote: "
        f"{[p.name for p in files_under(home)]}\n" + report(proc, "installer")
    )
    db_path = config_db_path(config_file)
    assert inside(home, db_path), f"the config under the data home points its database at {db_path}"
    assert Path(db_path).is_file(), f"the instance database was never created at {db_path}"
    assert log_files_under(home), (
        f"the instance wrote no log file under its own data home {home}: "
        f"{[p.as_posix() for p in files_under(home)]}"
    )

    # ...and nothing at all reached the default home (no silent split-brain).
    assert box.default_home_entries() == [], (
        "a run with KATAGIRI_DATA_HOME set still wrote to the default home: "
        f"{box.default_home_entries()}"
    )


def test_no_override_keeps_the_default_local_app_data_home(
    holdout, sandbox_factory, run_installer
):
    """US5/3 + FR-014 regression: with no override, today's behavior, unchanged.

    This is the one test in this module that must pass *before* the feature is
    implemented: it pins the pre-007 resolution so the instance work cannot
    move the existing install's data as a side effect. Deliberately narrow --
    the install chain itself is covered by test_stability_install.py.
    """
    box = sandbox_factory(config=False)
    box.use_default_home()
    assert "KATAGIRI_DATA_HOME" not in box.env(), "this test must run with no override at all"
    assert "KATAGIRI_CONFIG" not in box.env(), "this test must run with no override at all"

    proc = run_installer(box, "--yes")
    assert proc.returncode == 0, report(proc, "the installer with no override")

    expected = box.katagiri_dir / "config.toml"
    assert expected.is_file(), (
        f"with no override the config must land in %LOCALAPPDATA%\\Katagiri ({expected}); "
        f"found instead: {box.default_home_entries()}"
    )
    assert inside(box.katagiri_dir, config_db_path(expected)), (
        "with no override the database must stay under %LOCALAPPDATA%\\Katagiri: "
        + config_db_path(expected)
    )
    assert log_files_under(box.katagiri_dir), (
        "with no override the logs must stay under %LOCALAPPDATA%\\Katagiri\\logs; "
        f"found: {[p.as_posix() for p in files_under(box.katagiri_dir)]}"
    )


# ---------------------------------------------------------------------------
# FR-015 / FR-017 -- two instances share nothing
# ---------------------------------------------------------------------------


def test_two_data_homes_share_no_files_after_two_installs(
    holdout, tmp_path, sandbox_factory, run_installer
):
    """US5/1 + FR-015: installing the second instance neither reads nor writes the first.

    The first home is fingerprinted (every path, size and mtime) before the
    second install and compared afterwards: byte-untouched is the requirement,
    not merely "different paths".
    """
    first_box = sandbox_factory(config=False, seed=False)
    second_box = sandbox_factory(config=False, seed=False)
    first_home, first_seeded = make_home(tmp_path, holdout, "a")
    second_home, second_seeded = make_home(tmp_path, holdout, "b")
    first_box.use_data_home(first_home)
    second_box.use_data_home(second_home)

    first_run = run_installer(first_box, "--yes", timeout=budget(first_seeded))
    assert first_run.returncode == 0, report(first_run, "the first instance's installer")
    assert (first_home / "config.toml").is_file(), report(first_run, "the first instance")

    before = tree_fingerprint(first_home)
    assert before, f"the first instance produced nothing under {first_home}"

    second_run = run_installer(second_box, "--yes", timeout=budget(second_seeded))
    assert second_run.returncode == 0, report(second_run, "the second instance's installer")

    after = tree_fingerprint(first_home)
    added = sorted(set(after) - set(before))
    removed = sorted(set(before) - set(after))
    changed = sorted(key for key in set(before) & set(after) if before[key] != after[key])
    assert not added, f"installing instance B created {added} inside instance A's home"
    assert not removed, f"installing instance B deleted {removed} from instance A's home"
    assert not changed, f"installing instance B modified {changed} inside instance A's home"

    # The second instance is complete in its own home, and the two configs name
    # two different databases -- no shared file behind matching trees.
    second_config = second_home / "config.toml"
    assert second_config.is_file(), report(second_run, "the second instance")
    first_db = config_db_path(first_home / "config.toml")
    second_db = config_db_path(second_config)
    assert inside(second_home, second_db), second_db
    assert not same_path(first_db, second_db), (
        f"both instances point at one database: {second_db}"
    )
    assert not inside(first_home, second_db), (
        f"the second instance's config points into the first instance's home: {second_db}"
    )
    for box in (first_box, second_box):
        assert box.default_home_entries() == [], (
            f"an instance install leaked into the default home: {box.default_home_entries()}"
        )


def test_two_concurrent_servers_each_report_their_own_data_home(
    holdout, tmp_path, sandbox_factory, mcp_server
):
    """US5/2 + FR-016/FR-017: concurrent instances, told apart in one call each.

    Also the failure mode that matters operationally: one instance dying must
    not take the other's session with it.
    """
    first_box = sandbox_factory(config=False, seed=False)
    second_box = sandbox_factory(config=False, seed=False)
    first_home, _ = make_home(tmp_path, holdout, "live-a")
    second_home, _ = make_home(tmp_path, holdout, "live-b")
    first_box.use_data_home(first_home)
    second_box.use_data_home(second_home)

    client_a = mcp_server(first_box)
    client_b = mcp_server(second_box)
    payload_a = client_a.call_tool(TOOL)
    payload_b = client_b.call_tool(TOOL)

    for payload, home, label in ((payload_a, first_home, "A"), (payload_b, second_home, "B")):
        assert "data_home" in payload, f"instance {label} reports no data_home: {sorted(payload)}"
        assert same_path(payload["data_home"], home), (
            f"instance {label} reports data_home {payload['data_home']!r}, not its own {home}"
        )
        assert payload.get("data_home_source") == "env", (
            f"instance {label} resolved its home from KATAGIRI_DATA_HOME, so "
            f"data_home_source must be 'env', got {payload.get('data_home_source')!r}"
        )
        for field in ("config_path", "log_file_path"):
            assert inside(home, payload[field]), (
                f"instance {label} reports {field} outside its data home: {payload[field]}"
            )

    for field in ("data_home", "config_path", "db_path", "log_file_path", "pid"):
        assert payload_a[field] != payload_b[field], (
            f"two side-by-side instances report the same {field}: {payload_a[field]!r}"
        )
    assert not inside(first_home, payload_b["db_path"]), "instance B reports instance A's database"

    # Killing one instance leaves the other answering (SC-002 from a live session).
    client_a.process.kill()
    client_a.process.wait(timeout=15)
    assert client_a.process.poll() is not None, "instance A did not actually die"

    survivor = client_b.call_tool(TOOL)
    assert same_path(survivor["data_home"], second_home), survivor["data_home"]
    assert survivor["pid"] == payload_b["pid"], "the surviving instance was restarted, not survived"


def test_two_checkouts_pointed_at_one_data_home_report_the_same_home(
    holdout, tmp_path, sandbox_factory, mcp_server
):
    """Edge case: sharing one home is allowed, and must be *visible*, not hidden."""
    shared_home, _ = make_home(tmp_path, holdout, "shared")
    first_box = sandbox_factory(config=False, seed=False)
    second_box = sandbox_factory(config=False, seed=False)
    first_box.use_data_home(shared_home)
    second_box.use_data_home(shared_home)

    client_a = mcp_server(first_box)
    client_b = mcp_server(second_box)
    payload_a = client_a.call_tool(TOOL)
    payload_b = client_b.call_tool(TOOL)

    for payload, label in ((payload_a, "A"), (payload_b, "B")):
        assert payload["status"] == "ok", f"instance {label} did not answer cleanly: {payload}"
        assert same_path(payload["data_home"], shared_home), (
            f"instance {label} hides the shared home: {payload['data_home']!r}"
        )
        assert payload.get("data_home_source") == "env", payload.get("data_home_source")

    assert same_path(payload_a["config_path"], payload_b["config_path"]), (
        "two sessions on one data home must report the same config file: "
        f"{payload_a['config_path']!r} vs {payload_b['config_path']!r}"
    )
    assert same_path(payload_a["db_path"], payload_b["db_path"]), (
        f"{payload_a['db_path']!r} vs {payload_b['db_path']!r}"
    )
    assert payload_a["pid"] != payload_b["pid"], (
        "the two sessions must still be distinguishable as processes"
    )


# ---------------------------------------------------------------------------
# Precedence (research D9: KATAGIRI_CONFIG > KATAGIRI_DATA_HOME > default)
# ---------------------------------------------------------------------------


def test_katagiri_config_outranks_the_data_home_for_the_config_file_only(
    holdout, tmp_path, sandbox_factory, run_installer, mcp_server
):
    """D9 precedence: the file-specific override wins for the file; logs follow the home."""
    box = sandbox_factory(config=False, seed=False)
    home, seeded = make_home(tmp_path, holdout, "precedence")
    explicit_config = box.root / "explicit-instance-config.toml"
    box.use_data_home(home)
    # Re-assert the higher-precedence override on top of the data home.
    box.env_unset.discard("KATAGIRI_CONFIG")
    box.extra_env["KATAGIRI_CONFIG"] = str(explicit_config)

    proc = run_installer(box, "--yes", timeout=budget(seeded))
    assert proc.returncode == 0, report(proc, "the installer with both overrides set")

    assert explicit_config.is_file(), (
        f"KATAGIRI_CONFIG must still decide the config file's path ({explicit_config}); "
        f"the data home holds: {[p.name for p in files_under(home)]}"
    )
    assert not (home / "config.toml").exists(), (
        "the data home must not get a second config file when KATAGIRI_CONFIG names one"
    )
    assert log_files_under(home), (
        "logs follow the data home even when KATAGIRI_CONFIG points elsewhere; "
        f"the home holds: {[p.as_posix() for p in files_under(home)]}"
    )
    assert box.default_home_entries() == [], (
        f"the default home was written to anyway: {box.default_home_entries()}"
    )

    # The same precedence, as the diagnostic reports it.
    payload = mcp_server(box).call_tool(TOOL)
    assert same_path(payload["config_path"], explicit_config), payload["config_path"]
    assert same_path(payload["data_home"], home), payload["data_home"]
    assert inside(home, payload["log_file_path"]), payload["log_file_path"]


# ---------------------------------------------------------------------------
# FR-015 -- the installer flag, and the wiring it leaves behind
# ---------------------------------------------------------------------------


def test_the_data_home_flag_isolates_an_instance_with_no_environment_variable(
    holdout, tmp_path, sandbox_factory, run_installer_in_mirror, real_env_file_guard
):
    """FR-015: ``--data-home PATH`` alone gives the same isolation as the env var."""
    box = sandbox_factory(config=False, seed=False)
    box.use_default_home()  # no override in the environment: the flag is the whole story
    home, seeded = make_home(tmp_path, holdout, "flag")

    proc = run_installer_in_mirror(box, "--yes", "--data-home", str(home), timeout=budget(seeded))
    assert proc.returncode == 0, report(proc, "installer --data-home")

    config_file = home / "config.toml"
    assert config_file.is_file(), (
        f"--data-home must resolve the config under {home}; it holds "
        f"{[p.name for p in files_under(home)]}\n" + report(proc, "installer --data-home")
    )
    assert inside(home, config_db_path(config_file)), config_db_path(config_file)
    assert log_files_under(home), (
        f"--data-home must move the logs too; {home} holds "
        f"{[p.as_posix() for p in files_under(home)]}"
    )
    assert box.default_home_entries() == [], (
        f"--data-home still wrote to the default home: {box.default_home_entries()}"
    )


def test_the_data_home_flag_persists_the_instance_wiring_in_the_checkout(
    holdout, tmp_path, sandbox_factory, run_installer_in_mirror, real_env_file_guard,
    mirror_checkout
):
    """US5/4 + FR-015: a later launch from that folder inherits the instance.

    Interpretation (MANIFEST.md): the wiring file is the checkout's untracked
    ``agent/.env`` (research D9), and "the checkout" is whichever one the
    installer ran as -- so either the mirrored checkout's file or, if the
    implementation resolves the checkout from the installed package, the real
    one (whose content is read here and then byte-restored by the guard).
    Wherever it lands, the persisted value must name this instance's home, and
    nothing may be written to the default home.
    """
    box = sandbox_factory(config=False, seed=False)
    box.use_default_home()
    home, seeded = make_home(tmp_path, holdout, "wiring")

    proc = run_installer_in_mirror(box, "--yes", "--data-home", str(home), timeout=budget(seeded))
    assert proc.returncode == 0, report(proc, "installer --data-home")

    candidates = {
        "the mirrored checkout's agent/.env": (
            mirror_checkout.env_file.read_text(encoding="utf-8", errors="replace")
            if mirror_checkout.env_file.is_file()
            else ""
        ),
        # Only what this run added: a developer's real checkout may already be
        # wired to an instance of its own, which says nothing about this run.
        "the real checkout's agent/.env (lines this run added)": (
            real_env_file_guard.added_text()
        ),
    }
    wiring_lines = [
        (where, line)
        for where, text in candidates.items()
        for line in text.splitlines()
        if line.strip().startswith("KATAGIRI_DATA_HOME") and "=" in line
    ]
    assert wiring_lines, (
        "--data-home must persist the instance wiring in the checkout it ran in "
        "(KATAGIRI_DATA_HOME=... in agent/.env); neither candidate carries it.\n"
        + "\n".join(f"--- {where} ---\n{text}" for where, text in candidates.items())
        + "\n"
        + report(proc, "installer --data-home")
    )
    for where, line in wiring_lines:
        value = line.split("=", 1)[1].strip().strip('"').strip("'")
        assert value, f"{where} carries an empty KATAGIRI_DATA_HOME: {line!r}"
        assert same_path(value, home), (
            f"{where} wires the checkout to {value!r}, not to this instance's home {home}"
        )
    assert box.default_home_entries() == [], (
        f"the --data-home run wrote to the default home: {box.default_home_entries()}"
    )


# ---------------------------------------------------------------------------
# Edge cases: invalid override, absent directory
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("bad_value", ["", "   "], ids=["empty", "blank"])
def test_an_empty_data_home_override_fails_loudly_and_never_falls_back(
    holdout, sandbox_factory, run_installer, bad_value
):
    """Edge case: an invalid override is an explicit error, never a silent default.

    A silent fallback here is the dangerous failure: the operator believes they
    are working on a disposable instance while writing to the real study
    database (constitution III). So the assertion that matters is the second
    one -- the default home must stay empty.
    """
    box = sandbox_factory(config=False, seed=False)
    box.use_data_home(bad_value)

    proc = run_installer(box, "--yes", timeout=INSTALL_BUDGET)

    assert box.default_home_entries() == [], (
        "an invalid KATAGIRI_DATA_HOME silently fell back to the default home, which is "
        f"exactly what must never happen: {box.default_home_entries()}\n"
        + report(proc, "installer with an invalid data home")
    )
    assert proc.returncode != 0, report(
        proc, "installer with an invalid (empty) KATAGIRI_DATA_HOME"
    )
    told = (proc.stdout or "") + (proc.stderr or "")
    assert "KATAGIRI_DATA_HOME" in told, (
        "the rejection must name the override it is rejecting:\n"
        + report(proc, "installer with an invalid data home")
    )
    holdout.assert_no_traceback(told, where="the invalid-override rejection")


def test_a_relative_data_home_override_is_rejected_and_creates_nothing(
    holdout, sandbox_factory, run_installer_in_mirror, mirror_checkout
):
    """Edge case: a relative override is rejected, not resolved against the cwd.

    Run inside the mirrored checkout so that an implementation which *does*
    resolve it relatively creates its directory somewhere disposable -- and the
    test can still see that it happened.
    """
    box = sandbox_factory(config=False, seed=False)
    box.use_data_home(RELATIVE_HOME_NAME)

    proc = run_installer_in_mirror(box, "--yes", timeout=INSTALL_BUDGET)

    assert box.default_home_entries() == [], (
        "a relative KATAGIRI_DATA_HOME silently fell back to the default home: "
        f"{box.default_home_entries()}\n" + report(proc, "installer with a relative data home")
    )
    resolved = mirror_checkout.root / RELATIVE_HOME_NAME
    assert not resolved.exists(), (
        f"a relative override must be rejected, not resolved against the working directory "
        f"({resolved})\n" + report(proc, "installer with a relative data home")
    )
    assert not (holdout.REPO_ROOT / RELATIVE_HOME_NAME).exists(), (
        "a relative override was resolved against the real checkout"
    )
    assert proc.returncode != 0, report(proc, "installer with a relative data home")
    told = (proc.stdout or "") + (proc.stderr or "")
    assert "KATAGIRI_DATA_HOME" in told, (
        "the rejection must name the override it is rejecting:\n"
        + report(proc, "installer with a relative data home")
    )


def test_a_data_home_that_does_not_exist_yet_is_created_or_clearly_reported(
    holdout, tmp_path, sandbox_factory, run_installer
):
    """Edge case: "points at a not-yet-existing directory -> created, or reported, never a crash".

    Both outcomes are accepted, because the spec accepts both. What is not
    accepted: a crash, or a fallback that puts this instance's data in the
    default home.
    """
    box = sandbox_factory(config=False, seed=False)
    home, _ = make_home(tmp_path, holdout, "absent", create=False)
    assert not home.exists()
    box.use_data_home(home)

    proc = run_installer(box, "--yes", timeout=INSTALL_COLD_BUDGET)

    told = (proc.stdout or "") + (proc.stderr or "")
    holdout.assert_no_traceback(told, where="a run against an absent data home")
    assert box.default_home_entries() == [], (
        "an absent data home must not push this instance's data into the default home: "
        f"{box.default_home_entries()}\n" + report(proc, "installer with an absent data home")
    )

    if proc.returncode == 0:
        assert home.is_dir(), (
            "a successful run must have created the data home it was pointed at:\n"
            + report(proc, "installer with an absent data home")
        )
        assert (home / "config.toml").is_file(), (
            f"the created home holds no config: {[p.name for p in files_under(home)]}"
        )
        assert inside(home, config_db_path(home / "config.toml")), config_db_path(
            home / "config.toml"
        )
    else:
        assert home.name in told or str(home) in told, (
            "a refusal must name the directory it could not use:\n"
            + report(proc, "installer with an absent data home")
        )
        assert not files_under(home), (
            "a refused run left a half-built instance behind: "
            f"{[p.as_posix() for p in files_under(home)]}"
        )
