#!/usr/bin/env python3
"""Generate the mechanical rows of ``docs/assignment/tool-contracts.md``.

This is the T018 generator (spec 005-mcp-assignment, FR-012/FR-013): the
assignment's Part C table has 8 rows per tool. Four of them — Name,
Model-facing description, Input schema, Output schema — are *mechanical*:
they exist already, verbatim, in :mod:`katagiri.tool_registry` as each tool's
:class:`~katagiri.tool_registry.ToolSpec` and its :class:`ArgSpec` tuple.
Hand-copying them into a markdown file would let the doc drift from the
contract the MCP server actually honours, so this script emits them straight
from the registry instead. The remaining four rows — Purpose, Error
conditions, Side effects, Example — are prose that only a human can write
(T020); this script never touches them once they exist.

Delimiter contract
-------------------
Every tool gets two clearly marked blocks, in this exact order::

    <!-- BEGIN GENERATED: <tool> -->
    ... mechanical rows, rebuilt every run ...
    <!-- END GENERATED: <tool> -->
    <!-- BEGIN HAND: <tool> -->
    ... hand-written prose, read back and preserved byte-for-byte ...
    <!-- END HAND: <tool> -->

``<tool>`` is the bare tool name (e.g. ``ping``), matched literally on both
the BEGIN and END markers of a pair. A HAND block that does not yet exist for
a tool (first run, or a newly-registered tool) is seeded with
``_TODO (T020)_`` placeholder lines — one per hand row — so T020 has a
stable slot to fill in. Regeneration works by reading the previous version of
the doc (if any), lifting out every HAND block by name, and rebuilding the
whole file: GENERATED blocks are always freshly computed from the registry,
HAND blocks are copied forward unchanged (or seeded, if new). Tool order is
registry declaration order (``katagiri.tool_registry.TOOL_SPECS``), which is
stable, so a diff after a registry change touches only what actually changed.

Usage
-----
    python scripts/gen_tool_contracts.py            # regenerate and write
    python scripts/gen_tool_contracts.py --check     # verify only, write nothing

``--check`` regenerates the doc in memory and compares it against the
committed file. It prints the tool(s) whose GENERATED block disagrees and
exits 1 with a "run scripts/gen_tool_contracts.py" message; it never touches
the file on disk. Exit code is 0 when nothing would change.

Python 3.12+. Imports ``katagiri.tool_registry``, so it runs against
katagiri's own venv, not any agent subproject's.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    from katagiri.tool_registry import ArgSpec, ToolSpec, TOOL_SPECS
except ImportError:  # pragma: no cover - convenience for direct invocation
    _SRC = Path(__file__).resolve().parent.parent / "src"
    if str(_SRC) not in sys.path:
        sys.path.insert(0, str(_SRC))
    from katagiri.tool_registry import ArgSpec, ToolSpec, TOOL_SPECS

REPO_ROOT = Path(__file__).resolve().parent.parent
DOC_PATH = REPO_ROOT / "docs" / "assignment" / "tool-contracts.md"

HAND_PLACEHOLDER = "_TODO (T020)_"

HAND_ROWS: tuple[str, ...] = (
    "Purpose",
    "Error conditions",
    "Side effects",
    "Example",
)

_HAND_BLOCK_RE = re.compile(
    r"<!-- BEGIN HAND: (?P<name>\S+) -->\n(?P<body>.*?)\n<!-- END HAND: (?P=name) -->",
    re.DOTALL,
)

_HEADER = """\
# MCP tool contracts

Generated by `scripts/gen_tool_contracts.py` from `src/katagiri/tool_registry.py`
(spec 005-mcp-assignment, FR-012/FR-013). Every tool the server registers gets
one section below, in registry declaration order, with the assignment's 8-row
table split across two blocks:

* **GENERATED** — Name, Model-facing description, Input schema, Output schema.
  Rebuilt mechanically from `ToolSpec`/`ArgSpec` every run. Never hand-edit
  these lines: they will be overwritten, and the drift check
  (`tests/test_contract_docs.py`, and the pre-commit hook once T019 lands)
  fails the build if they disagree with the registry.
* **HAND** — Purpose, Error conditions, Side effects, Example. Written by a
  human (T020) and preserved byte-for-byte across regeneration.

Regenerate after any `tool_registry.py` change:

    python scripts/gen_tool_contracts.py

Check for drift without writing anything:

    python scripts/gen_tool_contracts.py --check
"""


def _format_args(args: tuple[ArgSpec, ...]) -> str:
    if not args:
        return "_none_"
    lines = []
    for arg in args:
        requirement = "required" if arg.required else "optional"
        summary = f" — {arg.summary}" if arg.summary else ""
        lines.append(f"- `{arg.name}` (`{arg.type}`, {requirement}){summary}")
    return "\n".join(lines)


def _generated_block(spec: ToolSpec) -> str:
    lines = [
        f"<!-- BEGIN GENERATED: {spec.name} -->",
        f"### `{spec.name}`",
        "",
        f"- **Name**: `{spec.name}`",
        f"- **Model-facing description**: {spec.summary}",
        "- **Input schema**:",
        _indent(_format_args(spec.args)),
        f"- **Output schema**: {spec.output}",
        f"<!-- END GENERATED: {spec.name} -->",
    ]
    return "\n".join(lines)


def _indent(block: str, prefix: str = "  ") -> str:
    return "\n".join(f"{prefix}{line}" for line in block.splitlines())


def _default_hand_block(name: str) -> str:
    lines = [f"<!-- BEGIN HAND: {name} -->"]
    for row in HAND_ROWS:
        lines.append(f"- **{row}**: {HAND_PLACEHOLDER}")
    lines.append(f"<!-- END HAND: {name} -->")
    return "\n".join(lines)


def _existing_hand_blocks(text: str) -> dict[str, str]:
    """Map tool name -> the exact HAND block text (markers included)."""
    blocks: dict[str, str] = {}
    for match in _HAND_BLOCK_RE.finditer(text):
        name = match.group("name")
        blocks[name] = (
            f"<!-- BEGIN HAND: {name} -->\n{match.group('body')}\n"
            f"<!-- END HAND: {name} -->"
        )
    return blocks


def render(existing_text: str | None) -> str:
    """Build the full document text.

    GENERATED blocks are always freshly computed from ``TOOL_SPECS``. HAND
    blocks are copied forward verbatim from ``existing_text`` when present,
    else seeded with the placeholder rows.
    """
    existing_hand = _existing_hand_blocks(existing_text) if existing_text else {}

    sections: list[str] = [_HEADER]
    for spec in TOOL_SPECS:
        hand_block = existing_hand.get(spec.name, _default_hand_block(spec.name))
        sections.append(_generated_block(spec) + "\n" + hand_block)
    return "\n\n".join(sections) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into memory and compare against the committed file; "
        "write nothing, exit 1 on drift",
    )
    args = parser.parse_args(argv)

    existing_text = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.is_file() else None
    rendered = render(existing_text)

    if args.check:
        if existing_text is None:
            print(
                f"DRIFT: {_display_path(DOC_PATH)} does not "
                "exist. Run scripts/gen_tool_contracts.py to create it."
            )
            return 1
        if rendered == existing_text:
            print("tool-contracts.md is up to date with tool_registry.py.")
            return 0
        drifted = _drifted_tools(existing_text, rendered)
        for name in drifted:
            print(f"DRIFT: generated block for '{name}' disagrees with the registry.")
        print(
            "tool-contracts.md is out of date. Run scripts/gen_tool_contracts.py "
            "to regenerate it."
        )
        return 1

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {_display_path(DOC_PATH)} ({len(TOOL_SPECS)} tools).")
    return 0


def _display_path(path: Path) -> str:
    """``path`` relative to the repo root when possible, else as given.

    Tests point ``DOC_PATH`` at a scratch file outside ``REPO_ROOT`` to induce
    drift without touching the committed doc; ``relative_to`` would raise
    there, and a display path is not worth failing over.
    """
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return str(path)


def _drifted_tools(existing_text: str, rendered: str) -> list[str]:
    """Best-effort list of tool names whose GENERATED block changed."""
    drifted = []
    for spec in TOOL_SPECS:
        marker = f"<!-- BEGIN GENERATED: {spec.name} -->"
        old_start = existing_text.find(marker)
        new_start = rendered.find(marker)
        if old_start == -1 or new_start == -1:
            drifted.append(spec.name)
            continue
        end_marker = f"<!-- END GENERATED: {spec.name} -->"
        old_end = existing_text.find(end_marker, old_start)
        new_end = rendered.find(end_marker, new_start)
        old_block = existing_text[old_start : old_end + len(end_marker)]
        new_block = rendered[new_start : new_end + len(end_marker)]
        if old_block != new_block:
            drifted.append(spec.name)
    return drifted


if __name__ == "__main__":
    sys.exit(main())
